### PR TITLE
[DRAFT] feat: copy suggestions

### PR DESCRIPTION
**Pull request by filipviz**
Some copy ideas & suggestions. TODO: finish about page

- We should decide on one term between "round participants", "supporters", and "contributors".
- Are we still using slicers?

---

### Detailed summary
- Renamed `emission` to `issuance` in `PieChart.tsx`
- Renamed `Others reserved` to `Other reserves` in `ReservedTable.tsx`
- Updated text in `ClaimSlicesButton.tsx` and `CreateFormAdvancedLinks.tsx`
- Updated text in `FullRedeemButton.tsx` and `Locks.tsx`
- Renamed `Others reserved` to `Other reserves` in `EmissionPreview.tsx`
- Updated text in `OwnerBlockToken.tsx` and `QueueBlock.tsx`
- Updated text in `CreateFormGeneral.tsx` and `CreateFormAdvancedReservedRate.tsx`
- Updated text in `OwnerBlock.tsx` and `CreateFormAdvancedERC20.tsx`
- Updated text in `CreateFormAdvancedLock.tsx` and `CreateFormAdvancedFundraise.tsx`
- Updated text in `HomeHowItWorks.tsx`
- Updated metadata in `about.tsx`

> The following files were skipped due to too many changes: `pages/about.tsx`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by jacopo-eth** [comment]
sweet, thanks for the PR!

- I usually go for round participants
- slice-related stuff is a remnant of the first version. kept in the codebase to not having to rewrite in case the components are needed in the future, but they shouldn't be used anywhere rn

Ideally I'd refactor the about page into an mdx component that can get imported using next/mdx. Tried to set it up but requires the app dir layout and it's taking me a while to get it done. will probably have to get back to it later

**Comment by filipviz** [comment]
Thanks @jjranalli. Made some further updates.

Would love your review on `pages/about.tsx` in particular – I want to make sure it's factual. Haven't done any styling for it – can't get dev server running.

**Comment by jacopo-eth** [comment]
this lgtm. can we merge? @filipviz

**Comment by filipviz** [comment]
SGTM @jjranalli

**Pull request merged**
